// src/flashcardData.js
// Dữ liệu Flashcard được biên soạn cho kỳ thi TOEIC.

export const decks = [
  {
    topic: "Corporate & Office Life 🏢",
    slug: "corporate-office",
    cards: [
      {
        id: "c1",
        word: "Negotiation",
        ipa: "/nəˌɡəʊʃiˈeɪʃn/",
        type: "noun",
        meaning: "Sự đàm phán, thương lượng",
        example: "The negotiation between the two companies was successful.",
      },
      {
        id: "c2",
        word: "Agenda",
        ipa: "/əˈdʒendə/",
        type: "noun",
        meaning: "Chương trình nghị sự",
        example: "Please review the agenda before the meeting starts.",
      },
      {
        id: "c3",
        word: "Deadline",
        ipa: "/ˈdedlaɪn/",
        type: "noun",
        meaning: "Hạn chót",
        example: "We need to finish this report by the deadline on Friday.",
      },
      {
        id: "c4",
        word: "Colleague",
        ipa: "/ˈkɒliːɡ/",
        type: "noun",
        meaning: "Đồng nghiệp",
        example:
          "I'm going to lunch with a colleague from the marketing department.",
      },
      {
        id: "c5",
        word: "Implement",
        ipa: "/ˈɪmplɪment/",
        type: "verb",
        meaning: "Thi hành, triển khai",
        example: "The new strategy will be implemented next month.",
      },
    ],
  },
  {
    topic: "Finance & Banking 💰",
    slug: "finance-banking",
    cards: [
      {
        id: "f1",
        word: "Investment",
        ipa: "/ɪnˈvestmənt/",
        type: "noun",
        meaning: "Sự đầu tư",
        example: "Real estate can be a very profitable investment.",
      },
      {
        id: "f2",
        word: "Revenue",
        ipa: "/ˈrevənjuː/",
        type: "noun",
        meaning: "Doanh thu",
        example: "The company's annual revenue has increased by 15%.",
      },
      {
        id: "f3",
        word: "Budget",
        ipa: "/ˈbʌdʒɪt/",
        type: "noun/verb",
        meaning: "Ngân sách",
        example: "We need to create a budget for the upcoming project.",
      },
      {
        id: "f4",
        word: "Invoice",
        ipa: "/ˈɪnvɔɪs/",
        type: "noun",
        meaning: "Hóa đơn",
        example: "Please pay the invoice within 30 days of receipt.",
      },
      {
        id: "f5",
        word: "Transaction",
        ipa: "/trænˈzækʃn/",
        type: "noun",
        meaning: "Giao dịch",
        example: "All bank transactions are recorded in this statement.",
      },
    ],
  },
  {
    topic: "Travel & Hospitality ✈️",
    slug: "travel-hospitality",
    cards: [
      {
        id: "tr1",
        word: "Itinerary",
        ipa: "/aɪˈtɪnərəri/",
        type: "noun",
        meaning: "Lịch trình, hành trình",
        example:
          "Our travel agent sent us the detailed itinerary for our trip to Japan.",
      },
      {
        id: "tr2",
        word: "Accommodation",
        ipa: "/əˌkɒməˈdeɪʃn/",
        type: "noun",
        meaning: "Chỗ ở",
        example: "The hotel provides excellent accommodation for its guests.",
      },
      {
        id: "tr3",
        word: "Reservation",
        ipa: "/ˌrezəˈveɪʃn/",
        type: "noun",
        meaning: "Sự đặt chỗ trước",
        example:
          "I'd like to make a dinner reservation for two people tonight.",
      },
      {
        id: "tr4",
        word: "Boarding Pass",
        ipa: "/ˈbɔːdɪŋ pɑːs/",
        type: "noun",
        meaning: "Thẻ lên máy bay",
        example: "You must show your boarding pass at the gate.",
      },
      {
        id: "tr5",
        word: "Concierge",
        ipa: "/ˌkɒnsiˈeəʒ/",
        type: "noun",
        meaning: "Nhân viên hướng dẫn (khách sạn)",
        example: "The concierge can help you book tickets for the show.",
      },
    ],
  },
  {
    topic: "Marketing & Sales 📈",
    slug: "marketing-sales",
    cards: [
      {
        id: "m1",
        word: "Campaign",
        ipa: "/kæmˈpeɪn/",
        type: "noun",
        meaning: "Chiến dịch",
        example: "Our new advertising campaign will launch next week.",
      },
      {
        id: "m2",
        word: "Consumer",
        ipa: "/kənˈsjuːmər/",
        type: "noun",
        meaning: "Người tiêu dùng",
        example: "We need to better understand consumer behavior.",
      },
      {
        id: "m3",
        word: "Brand",
        ipa: "/brænd/",
        type: "noun",
        meaning: "Thương hiệu",
        example: "Building a strong brand is crucial for long-term success.",
      },
      {
        id: "m4",
        word: "Launch",
        ipa: "/lɔːntʃ/",
        type: "verb/noun",
        meaning: "Ra mắt, tung ra",
        example: "The company plans to launch its new product in the spring.",
      },
      {
        id: "m5",
        word: "Demographics",
        ipa: "/ˌdeməˈɡræfɪks/",
        type: "noun",
        meaning: "Nhân khẩu học",
        example:
          "The marketing team analyzed the demographics of the target audience.",
      },
    ],
  },
];
