import React, { useState, useEffect, useRef } from "react";

// Danh sách từ vựng cho trò chơi
const wordList = [
  "ability",
  "about",
  "above",
  "accept",
  "across",
  "action",
  "admit",
  "affect",
  "again",
  "agree",
  "ahead",
  "allow",
  "almost",
  "alone",
  "along",
  "always",
  "amount",
  "animal",
  "answer",
  "appear",
  "apply",
  "around",
  "arrive",
  "article",
  "attack",
  "author",
  "avoid",
  "beautiful",
  "become",
  "because",
  "before",
  "begin",
  "behave",
  "behind",
  "believe",
  "benefit",
  "between",
  "beyond",
  "billion",
  "blood",
  "board",
  "bring",
  "build",
  "business",
  "camera",
  "cancer",
  "capital",
  "career",
  "carry",
  "catch",
  "cause",
  "center",
  "central",
  "century",
  "certain",
  "chair",
  "challenge",
  "chance",
  "change",
  "charge",
  "check",
  "child",
  "choice",
  "choose",
  "church",
  "citizen",
  "claim",
  "clear",
  "close",
  "coach",
  "collect",
  "college",
  "color",
  "come",
  "common",
  "community",
  "company",
  "compare",
  "computer",
  "concern",
  "condition",
  "conference",
  "consider",
  "contain",
  "continue",
  "control",
  "could",
  "country",
  "couple",
  "course",
  "court",
  "cover",
  "create",
  "crime",
  "culture",
  "current",
  "customer",
  "dark",
  "data",
  "daughter",
  "death",
  "debate",
  "decade",
  "decide",
  "decision",
  "deep",
  "degree",
  "democrat",
  "describe",
  "design",
  "despite",
  "detail",
  "determine",
  "develop",
  "die",
  "difference",
  "difficult",
  "dinner",
  "direction",
  "discover",
  "discuss",
  "disease",
  "doctor",
  "drive",
  "during",
  "early",
  "east",
  "easy",
  "economic",
  "economy",
  "edge",
  "education",
  "effect",
  "effort",
  "either",
  "election",
  "employee",
  "energy",
  "enjoy",
  "enough",
  "enter",
  "entire",
  "environment",
  "especially",
  "establish",
  "evening",
  "event",
  "every",
  "evidence",
  "exactly",
  "example",
  "exist",
  "expect",
  "experience",
  "expert",
  "explain",
  "family",
  "father",
  "federal",
  "feel",
  "field",
  "fight",
  "figure",
  "fill",
  "final",
  "financial",
  "find",
  "fine",
  "finish",
  "firm",
  "first",
  "floor",
  "focus",
  "follow",
  "force",
  "foreign",
  "forget",
  "form",
  "former",
  "forward",
  "friend",
  "front",
  "fund",
  "future",
  "game",
  "garden",
  "general",
  "generation",
  "give",
  "glass",
  "goal",
  "good",
  "government",
  "great",
  "green",
  "ground",
  "group",
  "grow",
  "growth",
  "guess",
  "happy",
  "hard",
  "have",
  "head",
  "health",
  "hear",
  "heart",
  "help",
  "herself",
  "high",
  "history",
  "hold",
  "home",
  "hope",
  "hospital",
  "hotel",
  "hour",
  "house",
  "however",
  "human",
  "hundred",
  "husband",
  "idea",
  "identify",
  "image",
  "imagine",
  "impact",
  "important",
  "improve",
  "include",
  "increase",
  "indeed",
  "indicate",
  "industry",
  "information",
  "inside",
  "instead",
  "interest",
  "international",
  "interview",
  "into",
  "investment",
  "involve",
  "issue",
  "item",
  "itself",
  "join",
  "just",
  "keep",
  "kill",
  "kind",
  "kitchen",
  "know",
  "knowledge",
  "land",
  "language",
  "large",
  "last",
  "late",
  "later",
  "laugh",
  "launch",
  "lead",
  "leader",
  "learn",
  "least",
  "leave",
  "left",
  "legal",
  "less",
  "letter",
  "level",
  "life",
  "light",
  "like",
  "line",
  "list",
  "listen",
  "live",
  "local",
  "long",
  "look",
  "lose",
  "love",
  "machine",
  "magazine",
  "main",
  "maintain",
  "major",
  "make",
  "manage",
  "manager",
  "many",
  "market",
  "marriage",
  "material",
  "matter",
  "maybe",
  "mean",
  "measure",
  "media",
  "medical",
  "meet",
  "meeting",
  "member",
  "memory",
  "mention",
  "message",
  "method",
  "middle",
  "might",
  "military",
  "million",
  "mind",
  "minute",
  "miss",
  "mission",
  "model",
  "modern",
  "moment",
  "money",
  "month",
  "more",
  "morning",
  "most",
  "mother",
  "mouth",
  "move",
  "movement",
  "movie",
  "music",
  "myself",
  "name",
  "nation",
  "national",
  "natural",
  "nature",
  "near",
  "nearly",
  "necessary",
  "need",
  "network",
  "never",
  "news",
  "newspaper",
  "next",
  "nice",
  "night",
  "north",
  "note",
  "nothing",
  "notice",
  "number",
  "occur",
  "offer",
  "office",
  "officer",
  "official",
  "often",
  "once",
  "only",
  "open",
  "operation",
  "opportunity",
  "option",
  "order",
  "organization",
  "other",
  "others",
  "outside",
  "over",
  "owner",
  "page",
  "pain",
  "painting",
  "paper",
  "parent",
  "part",
  "participant",
  "particular",
  "partner",
  "party",
  "pass",
  "past",
  "patient",
  "pattern",
  "peace",
  "people",
  "performance",
  "perhaps",
  "period",
  "person",
  "personal",
  "phone",
  "physical",
  "pick",
  "picture",
  "piece",
  "place",
  "plan",
  "plant",
  "play",
  "player",
  "point",
  "police",
  "policy",
  "political",
  "politics",
  "poor",
  "popular",
  "population",
  "position",
  "positive",
  "possible",
  "power",
  "practice",
  "prepare",
  "present",
  "president",
  "pressure",
  "pretty",
  "prevent",
  "price",
  "private",
  "probably",
  "problem",
  "process",
  "produce",
  "product",
  "production",
  "professional",
  "professor",
  "program",
  "project",
  "property",
  "protect",
  "prove",
  "provide",
  "public",
  "pull",
  "purpose",
  "push",
  "put",
  "quality",
  "question",
  "quickly",
  "quite",
  "race",
  "radio",
  "raise",
  "range",
  "rate",
  "rather",
  "reach",
  "read",
  "ready",
  "real",
  "reality",
  "realize",
  "really",
  "reason",
  "receive",
  "recent",
  "recently",
  "recognize",
  "record",
  "reduce",
  "reflect",
  "region",
  "relate",
  "relationship",
  "religious",
  "remain",
  "remember",
  "remove",
  "report",
  "represent",
  "republican",
  "require",
  "research",
  "resource",
  "respond",
  "response",
  "responsibility",
  "rest",
  "result",
  "return",
  "reveal",
  "rich",
  "right",
  "rise",
  "risk",
  "road",
  "rock",
  "role",
  "room",
  "rule",
  "safe",
  "same",
  "save",
  "school",
  "science",
  "scientist",
  "score",
  "sea",
  "season",
  "seat",
  "second",
  "section",
  "security",
  "see",
  "seek",
  "seem",
  "sell",
  "send",
  "senior",
  "sense",
  "series",
  "serious",
  "serve",
  "service",
  "set",
  "seven",
  "several",
  "shake",
  "share",
  "shoot",
  "short",
  "shot",
  "should",
  "shoulder",
  "show",
  "side",
  "sign",
  "significant",
  "similar",
  "simple",
  "simply",
  "since",
  "sing",
  "single",
  "sister",
  "site",
  "situation",
  "size",
  "skill",
  "skin",
  "small",
  "smile",
  "social",
  "society",
  "soldier",
  "some",
  "somebody",
  "someone",
  "something",
  "sometimes",
  "song",
  "soon",
  "sort",
  "sound",
  "source",
  "south",
  "southern",
  "space",
  "speak",
  "special",
  "specific",
  "speech",
  "spend",
  "sport",
  "spring",
  "staff",
  "stage",
  "stand",
  "standard",
  "star",
  "start",
  "state",
  "statement",
  "station",
  "stay",
  "step",
  "still",
  "stock",
  "stop",
  "store",
  "story",
  "strategy",
  "street",
  "strong",
  "structure",
  "student",
  "study",
  "stuff",
  "style",
  "subject",
  "success",
  "successful",
  "such",
  "suddenly",
  "suffer",
  "suggest",
  "summer",
  "support",
  "sure",
  "surface",
  "system",
  "table",
  "take",
  "talk",
  "task",
  "teach",
  "teacher",
  "team",
  "technology",
  "television",
  "tell",
  "tend",
  "term",
  "test",
  "than",
  "thank",
  "that",
  "their",
  "them",
  "themselves",
  "then",
  "theory",
  "there",
  "these",
  "they",
  "thing",
  "think",
  "third",
  "this",
  "those",
  "though",
  "thought",
  "thousand",
  "threat",
  "three",
  "through",
  "throughout",
  "throw",
  "thus",
  "time",
  "today",
  "together",
  "tonight",
  "total",
  "tough",
  "toward",
  "town",
  "trade",
  "traditional",
  "training",
  "travel",
  "treat",
  "treatment",
  "tree",
  "trial",
  "trip",
  "trouble",
  "true",
  "truth",
  "turn",
  "type",
  "under",
  "understand",
  "unit",
  "until",
  "upon",
  "usually",
  "value",
  "various",
  "very",
  "victim",
  "view",
  "violence",
  "visit",
  "voice",
  "vote",
  "wait",
  "walk",
  "wall",
  "want",
  "watch",
  "water",
  "weapon",
  "wear",
  "week",
  "weight",
  "well",
  "west",
  "western",
  "what",
  "whatever",
  "when",
  "where",
  "whether",
  "which",
  "while",
  "white",
  "whole",
  "whom",
  "whose",
  "wide",
  "wife",
  "will",
  "wind",
  "window",
  "with",
  "within",
  "without",
  "woman",
  "wonder",
  "word",
  "work",
  "worker",
  "world",
  "worry",
  "would",
  "write",
  "writer",
  "wrong",
  "yard",
  "yeah",
  "year",
  "young",
  "your",
  "yourself",
];

const GAME_DURATION = 10000; // Thời gian chơi: 60 giây

export default function TypingGame() {
  const [words, setWords] = useState([]);
  const [currentWordIndex, setCurrentWordIndex] = useState(0);
  const [typedValue, setTypedValue] = useState("");
  const [score, setScore] = useState(0);
  const [timeLeft, setTimeLeft] = useState(GAME_DURATION);
  const [isGameRunning, setIsGameRunning] = useState(false);

  const inputRef = useRef(null);

  // Khởi tạo và xáo trộn danh sách từ
  useEffect(() => {
    setWords(shuffleArray(wordList));
  }, []);

  // Xử lý bộ đếm thời gian
  useEffect(() => {
    let interval;
    if (isGameRunning && timeLeft > 0) {
      interval = setInterval(() => {
        setTimeLeft((prevTime) => prevTime - 1);
      }, 1000);
    } else if (timeLeft === 0) {
      setIsGameRunning(false);
    }
    return () => clearInterval(interval);
  }, [isGameRunning, timeLeft]);

  // Tự động focus vào ô input khi game bắt đầu
  useEffect(() => {
    if (isGameRunning) {
      inputRef.current.focus();
    }
  }, [isGameRunning]);

  const shuffleArray = (array) => [...array].sort(() => Math.random() - 0.5);

  const startGame = () => {
    setWords(shuffleArray(wordList));
    setIsGameRunning(true);
    setTimeLeft(GAME_DURATION);
    setScore(0);
    setCurrentWordIndex(0);
    setTypedValue("");
  };

  const handleInputChange = (e) => {
    const newTypedValue = e.target.value;

    // Không cho phép gõ space ở đầu
    if (newTypedValue.trim() === "") {
      setTypedValue("");
      return;
    }

    setTypedValue(newTypedValue);

    // Kiểm tra khi người dùng gõ xong từ và nhấn space
    if (newTypedValue.endsWith(" ")) {
      const typedWord = newTypedValue.trim();
      if (typedWord === words[currentWordIndex]) {
        setScore(score + 1);
        setCurrentWordIndex(currentWordIndex + 1);
        setTypedValue(""); // Xóa ô input để gõ từ mới
      }
    }
  };

  const currentWord = words[currentWordIndex];

  return (
    <div className="flex h-screen flex-col items-center justify-center p-4 font-mono">
      <div className="w-full max-w-3xl">
        <h1 className="text-center text-4xl font-bold text-yellow-400 mb-8">
          Typing Speedster ⚡
        </h1>

        {isGameRunning ? (
          <div>
            {/* Header thông số game */}
            <div className="mb-8 flex justify-around text-2xl">
              <div className="text-center">
                <p className="text-gray-400">Time Left</p>
                <p className="text-5xl font-bold text-yellow-400">{timeLeft}</p>
              </div>
              <div className="text-center">
                <p className="text-gray-400">Score</p>
                <p className="text-5xl font-bold text-green-400">{score}</p>
              </div>
            </div>

            {/* Khu vực hiển thị từ */}
            <div className="relative mb-8 flex h-20 items-center justify-center rounded-lg bg-gray-700 p-4 text-3xl tracking-widest">
              {currentWord?.split("").map((char, index) => {
                let charClass = "text-gray-400";
                if (index < typedValue.length) {
                  charClass =
                    typedValue[index] === char
                      ? "text-green-400"
                      : "text-red-500 underline";
                }
                return (
                  <span key={index} className={charClass}>
                    {char}
                  </span>
                );
              })}
            </div>

            {/* Ô nhập liệu */}
            <input
              ref={inputRef}
              type="text"
              value={typedValue}
              onChange={handleInputChange}
              className="w-full rounded-lg border-2 border-gray-600 bg-gray-800 p-4 text-center text-2xl text-white outline-none focus:border-yellow-400"
              placeholder="Start typing here..."
              autoComplete="off"
              autoCapitalize="off"
              autoCorrect="off"
            />
          </div>
        ) : (
          // Màn hình bắt đầu / kết thúc
          <div className="text-center">
            {score > 0 ? ( // Màn hình kết thúc
              <div>
                <h2 className="text-3xl font-bold text-green-400">
                  Time's up!
                </h2>
                <p className="mt-4 text-xl">Your final score is:</p>
                <p className="my-6 text-8xl font-bold">{score}</p>
                <p className="text-lg">
                  That's approximately{" "}
                  <span className="text-yellow-400 font-bold">{score} WPM</span>{" "}
                  (Words Per Minute)!
                </p>
              </div>
            ) : (
              // Màn hình bắt đầu
              <div>
                <h2 className="text-2xl">
                  Type all the words you can in 60 seconds.
                </h2>
                <p className="mt-2 text-gray-400">
                  Type the word and press{" "}
                  <span className="font-bold text-yellow-400">Spacebar</span> to
                  move to the next one.
                </p>
              </div>
            )}
            <button
              onClick={startGame}
              className="mt-12 rounded-lg bg-yellow-400 px-10 py-4 text-2xl font-bold text-gray-900 transition-transform hover:scale-105"
            >
              {score > 0 ? "Play Again" : "Start Game"}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
