const vocabImages = [
  // 5 câu hỏi gốc
  {
    image: "https://images.unsplash.com/photo-1579613832125-5d34a13ffe2a?w=800",
    options: ["Banana", "Apple", "Orange", "Grape"],
    correctAnswer: "Apple",
    ipa: "/ˈæpəl/",
    type: "noun",
    meaning: "Quả táo",
    example: "An apple a day keeps the doctor away.",
  },
  {
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
    options: ["Bicycle", "Bus", "Car", "Motorbike"],
    correctAnswer: "Car",
    ipa: "/kɑːr/",
    type: "noun",
    meaning: "Xe hơi",
    example: "He bought a new electric car.",
  },
  {
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800",
    options: ["Cat", "Dog", "Lion", "Tiger"],
    correctAnswer: "Dog",
    ipa: "/dɔːɡ/",
    type: "noun",
    meaning: "Con chó",
    example: "The dog is known as man's best friend.",
  },
  {
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800",
    options: ["Newspaper", "Magazine", "Book", "Notebook"],
    correctAnswer: "Book",
    ipa: "/bʊk/",
    type: "noun",
    meaning: "Quyển sách",
    example: "I am reading a very interesting book.",
  },
  {
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
    options: ["Pizza", "Burger", "Salad", "Pasta"],
    correctAnswer: "Pizza",
    ipa: "/ˈpiːtsə/",
    type: "noun",
    meaning: "Bánh pizza",
    example: "Let's order a pizza for dinner tonight.",
  },

  // Động vật
  {
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800",
    options: ["Dog", "Cat", "Bird", "Fish"],
    correctAnswer: "Cat",
    ipa: "/kæt/",
    type: "noun",
    meaning: "Con mèo",
    example: "My cat loves to nap in the sun.",
  },
  {
    image:
      "https://images.unsplash.com/flagged/photo-1557296126-953ce119454c?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEzfHx8ZW58MHx8fHx8",
    options: ["Horse", "Cow", "Sheep", "Goat"],
    correctAnswer: "Horse",
    ipa: "/hɔːrs/",
    type: "noun",
    meaning: "Con ngựa",
    example: "She learned to ride a horse when she was young.",
  },
  {
    image: "https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=800",
    options: ["Shark", "Dolphin", "Whale", "Turtle"],
    correctAnswer: "Turtle",
    ipa: "/ˈtɜːrtl/",
    type: "noun",
    meaning: "Con rùa",
    example: "The sea turtle swam gracefully through the water.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4-Z7b8Y0Xq4wGKvNf5jyrRnrGJmIXUvYpHg&s",
    options: ["Elephant", "Lion", "Giraffe", "Zebra"],
    correctAnswer: "Elephant",
    ipa: "/ˈelɪfənt/",
    type: "noun",
    meaning: "Con voi",
    example: "The elephant is the largest land animal.",
  },
  {
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800",
    options: ["Panda", "Koala", "Bear", "Monkey"],
    correctAnswer: "Panda",
    ipa: "/ˈpændə/",
    type: "noun",
    meaning: "Gấu trúc",
    example: "A panda's diet consists almost entirely of bamboo.",
  },
  {
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800",
    options: ["Wolf", "Fox", "Bear", "Deer"],
    correctAnswer: "Fox",
    ipa: "/fɑːks/",
    type: "noun",
    meaning: "Con cáo",
    example: "The quick brown fox jumps over the lazy dog.",
  },
  {
    image:
      "https://images.unsplash.com/photo-1497671954146-59a89ff626ff?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZmlzaHxlbnwwfHwwfHx8MA%3D%3D",
    options: ["Fish", "Crab", "Octopus", "Jellyfish"],
    correctAnswer: "Fish",
    ipa: "/fɪʃ/",
    type: "noun",
    meaning: "Con cá",
    example: "There are many colorful fish in the aquarium.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBKPSUxLMMpK5PtNpnvsGGko68aj4oBOFiVg&s",
    options: ["Parrot", "Eagle", "Owl", "Penguin"],
    correctAnswer: "Owl",
    ipa: "/aʊl/",
    type: "noun",
    meaning: "Con cú",
    example: "An owl is a nocturnal bird of prey.",
  },
  {
    image: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800",
    options: ["Puppy", "Kitten", "Cub", "Fawn"],
    correctAnswer: "Puppy",
    ipa: "/ˈpʌpi/",
    type: "noun",
    meaning: "Chó con",
    example: "We adopted an adorable puppy from the shelter.",
  },
  {
    image: "https://cdn.britannica.com/72/45872-050-10F6A603/Green-frog.jpg",
    options: ["Snake", "Lizard", "Crocodile", "Frog"],
    correctAnswer: "Frog",
    ipa: "/frɔːɡ/",
    type: "noun",
    meaning: "Con ếch",
    example: "A frog can live both in water and on land.",
  },

  // Trái cây & Rau củ
  {
    image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=800",
    options: ["Apple", "Banana", "Cherry", "Date"],
    correctAnswer: "Banana",
    ipa: "/bəˈnænə/",
    type: "noun",
    meaning: "Quả chuối",
    example: "A banana is a good source of potassium.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_L3sa3rTZbQ_uZu46oeZLKPCSt6azXIqdeg&s",
    options: ["Grape", "Strawberry", "Blueberry", "Raspberry"],
    correctAnswer: "Strawberry",
    ipa: "/ˈstrɔːberi/",
    type: "noun",
    meaning: "Quả dâu tây",
    example: "I love the taste of fresh strawberry.",
  },
  {
    image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=800",
    options: ["Pineapple", "Mango", "Papaya", "Kiwi"],
    correctAnswer: "Pineapple",
    ipa: "/ˈpaɪnæpəl/",
    type: "noun",
    meaning: "Quả dứa (thơm)",
    example: "Pineapple juice is very refreshing.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSmYFw92ZAvvl1xCJo3XYataUgNkUMXtqvPQ&s",
    options: ["Watermelon", "Cantaloupe", "Honeydew", "Melon"],
    correctAnswer: "Watermelon",
    ipa: "/ˈwɔːtərmelən/",
    type: "noun",
    meaning: "Dưa hấu",
    example: "Watermelon is perfect for a hot summer day.",
  },
  {
    image:
      "https://ripeme.com/wp-content/uploads/RF-10046-RIPE-ORGANIC-ORGANIC-ORANGES.jpg",
    options: ["Lemon", "Lime", "Orange", "Grapefruit"],
    correctAnswer: "Orange",
    ipa: "/ˈɔːrɪndʒ/",
    type: "noun",
    meaning: "Quả cam",
    example: "An orange is packed with vitamin C.",
  },
  {
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800",
    options: ["Carrot", "Potato", "Onion", "Garlic"],
    correctAnswer: "Carrot",
    ipa: "/ˈkærət/",
    type: "noun",
    meaning: "Củ cà rốt",
    example: "Rabbits love to eat a fresh carrot.",
  },
  {
    image:
      "https://domf5oio6qrcr.cloudfront.net/medialibrary/5390/h1218g16207258089583.jpg",
    options: ["Broccoli", "Cauliflower", "Cabbage", "Lettuce"],
    correctAnswer: "Broccoli",
    ipa: "/ˈbrɑːkəli/",
    type: "noun",
    meaning: "Bông cải xanh",
    example: "Broccoli is a very healthy green vegetable.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3bltTqTnZfOdpVPYdhlWKjd1sfJ9InXZ7Zw&s",
    options: ["Corn", "Pea", "Bean", "Asparagus"],
    correctAnswer: "Corn",
    ipa: "/kɔːrn/",
    type: "noun",
    meaning: "Bắp (ngô)",
    example: "We had corn on the cob at the barbecue.",
  },
  {
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800",
    options: ["Mushroom", "Pepper", "Eggplant", "Potato"],
    correctAnswer: "Potato",
    ipa: "/pəˈteɪtoʊ/",
    type: "noun",
    meaning: "Khoai tây",
    example: "French fries are made from a potato.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQftLJuX-6orikcx8RyLOIbl9BQkJvR0OCihg&s",
    options: ["Tomato", "Cucumber", "Zucchini", "Pumpkin"],
    correctAnswer: "Tomato",
    ipa: "/təˈmeɪtoʊ/",
    type: "noun",
    meaning: "Cà chua",
    example: "Is a tomato technically a fruit or a vegetable?",
  },

  // Thiên nhiên
  {
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800",
    options: ["Mountain", "River", "Forest", "Desert"],
    correctAnswer: "River",
    ipa: "/ˈrɪvər/",
    type: "noun",
    meaning: "Dòng sông",
    example: "The Nile is the longest river in the world.",
  },
  {
    image: "https://images.unsplash.com/photo-1454789548928-9efd52dc4031?w=800",
    options: ["Sun", "Moon", "Star", "Cloud"],
    correctAnswer: "Moon",
    ipa: "/muːn/",
    type: "noun",
    meaning: "Mặt trăng",
    example: "The full moon was shining brightly.",
  },
  {
    image: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=800",
    options: ["Rain", "Snow", "Wind", "Fog"],
    correctAnswer: "Rain",
    ipa: "/reɪn/",
    type: "noun",
    meaning: "Cơn mưa",
    example: "The sound of rain is very relaxing.",
  },
  {
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    options: ["Lake", "Ocean", "Pond", "Waterfall"],
    correctAnswer: "Lake",
    ipa: "/leɪk/",
    type: "noun",
    meaning: "Hồ nước",
    example: "We went for a swim in the lake.",
  },
  {
    image: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=800",
    options: ["Jungle", "Forest", "Wood", "Grove"],
    correctAnswer: "Forest",
    ipa: "/ˈfɔːrɪst/",
    type: "noun",
    meaning: "Khu rừng",
    example: "The Amazon is a vast tropical forest.",
  },
  {
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=800",
    options: ["Sunrise", "Sunset", "Dawn", "Dusk"],
    correctAnswer: "Sunrise",
    ipa: "/ˈsʌnraɪz/",
    type: "noun",
    meaning: "Bình minh",
    example: "Waking up early to see the sunrise is a beautiful experience.",
  },
  {
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800",
    options: ["Bird", "Horse", "Daisy", "Flower"],
    correctAnswer: "Flower",
    ipa: "/ˈflaʊər/",
    type: "noun",
    meaning: "Bông hoa",
    example: "He gave her a beautiful flower.",
  },
  {
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    options: ["Tree", "Bush", "Grass", "Leaf"],
    correctAnswer: "Tree",
    ipa: "/triː/",
    type: "noun",
    meaning: "Cái cây",
    example: "That old oak tree has been here for centuries.",
  },
  {
    image: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=800",
    options: ["Plant", "Root", "Stem", "Branch"],
    correctAnswer: "Plant",
    ipa: "/plænt/",
    type: "noun",
    meaning: "Thực vật",
    example: "You need to water this house plant regularly.",
  },
  {
    image: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800",
    options: ["Path", "Road", "Street", "Avenue"],
    correctAnswer: "Path",
    ipa: "/pæθ/",
    type: "noun",
    meaning: "Lối mòn",
    example: "Follow the stone path to the garden.",
  },

  // Đồ vật
  {
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=800",
    options: ["Shoe", "Boot", "Sandal", "Slipper"],
    correctAnswer: "Shoe",
    ipa: "/ʃuː/",
    type: "noun",
    meaning: "Chiếc giày",
    example: "I need to buy a new pair of running shoes.",
  },
  {
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
    options: ["Clock", "Watch", "Timer", "Alarm"],
    correctAnswer: "Watch",
    ipa: "/wɑːtʃ/",
    type: "noun",
    meaning: "Đồng hồ đeo tay",
    example: "He checked his watch to see the time.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq4ixBdbBFL_NZQd4m_2MrBXmwZNHPeaLuPg&s",
    options: ["Chair", "Table", "Sofa", "Bed"],
    correctAnswer: "Chair",
    ipa: "/tʃer/",
    type: "noun",
    meaning: "Cái ghế",
    example: "This wooden chair is very comfortable.",
  },
  {
    image: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=800",
    options: ["Phone", "Tablet", "Laptop", "Desktop"],
    correctAnswer: "Laptop",
    ipa: "/ˈlæptɑːp/",
    type: "noun",
    meaning: "Máy tính xách tay",
    example: "She uses her laptop for work and study.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwLfgncRLtqDZYC8RFAClwqFRhnJCfRwdTCA&s",
    options: ["Key", "Lock", "Door", "Window"],
    correctAnswer: "Key",
    ipa: "/kiː/",
    type: "noun",
    meaning: "Chìa khóa",
    example: "I lost my house key yesterday.",
  },
  {
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800",
    options: ["Camera", "Lens", "Flash", "Tripod"],
    correctAnswer: "Camera",
    ipa: "/ˈkæmərə/",
    type: "noun",
    meaning: "Máy ảnh",
    example: "This digital camera takes high-quality photos.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJpns3XVVMhoFgAgvhaXgEGVI7rR9r-PfBBA&s",
    options: ["Guitar", "Piano", "Violin", "Drum"],
    correctAnswer: "Guitar",
    ipa: "/ɡɪˈtɑːr/",
    type: "noun",
    meaning: "Đàn ghi-ta",
    example: "He is learning to play the acoustic guitar.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIGOFiyOOUK-CcPZd8o-XGgRYYJlzfQlPZzg&s",
    options: ["Cup", "Mug", "Glass", "Bottle"],
    correctAnswer: "Mug",
    ipa: "/mʌɡ/",
    type: "noun",
    meaning: "Cốc sứ",
    example: "I like to drink hot chocolate from my favorite mug.",
  },
  {
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800",
    options: ["Sneakers", "Heels", "Flats", "Boots"],
    correctAnswer: "Sneakers",
    ipa: "/ˈsniːkərz/",
    type: "noun",
    meaning: "Giày thể thao",
    example: "A good pair of sneakers is essential for sports.",
  },
  {
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800",
    options: ["Glasses", "Sunglasses", "Goggles", "Monocle"],
    correctAnswer: "Glasses",
    ipa: "/ˈɡlæsɪz/",
    type: "noun",
    meaning: "Kính mắt",
    example: "She wears glasses to help her see better.",
  },
  // Đồ vật (tiếp theo)
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFmOucOs0GcdfHqpk3F_LWDjCgc-dweI_mTw&s",
    options: ["Pen", "Pencil", "Marker", "Crayon"],
    correctAnswer: "Pen",
    ipa: "/pen/",
    type: "noun",
    meaning: "Bút mực",
    example: "May I borrow your pen to sign this document?",
  },
  {
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
    options: ["Running Shoe", "Sandal", "Boot", "Loafer"],
    correctAnswer: "Running Shoe",
    ipa: "/ˈrʌnɪŋ ʃuː/",
    type: "noun",
    meaning: "Giày chạy bộ",
    example: "This running shoe provides excellent support.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSraO8MCUmnhF0veyjUksGyL7z6Z8FTahdWBg&s",
    options: ["Couch", "Armchair", "Bench", "Stool"],
    correctAnswer: "Couch",
    ipa: "/kaʊtʃ/",
    type: "noun",
    meaning: "Ghế sô-pha",
    example: "The family gathered on the couch to watch a movie.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3_EV7KYkXuIKF8S0raB0axKQ_6e6cHlvIuw&s",
    options: ["Backpack", "Handbag", "Suitcase", "Wallet"],
    correctAnswer: "Backpack",
    ipa: "/ˈbækpæk/",
    type: "noun",
    meaning: "Ba lô",
    example: "He put his books and laptop in his backpack.",
  },
  {
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    options: ["Headphones", "Earbuds", "Speaker", "Microphone"],
    correctAnswer: "Headphones",
    ipa: "/ˈhedfoʊnz/",
    type: "noun",
    meaning: "Tai nghe",
    example: "She uses noise-cancelling headphones to focus.",
  },
  {
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800",
    options: ["Keyboard", "Mouse", "Monitor", "Printer"],
    correctAnswer: "Keyboard",
    ipa: "/ˈkiːbɔːrd/",
    type: "noun",
    meaning: "Bàn phím",
    example: "My mechanical keyboard is very satisfying to type on.",
  },
  {
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800",
    options: ["Bicycle", "Scooter", "Skateboard", "Rollerblade"],
    correctAnswer: "Bicycle",
    ipa: "/ˈbaɪsɪkl/",
    type: "noun",
    meaning: "Xe đạp",
    example: "Riding a bicycle is an environmentally friendly way to travel.",
  },
  {
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800",
    options: ["Bed", "Pillow", "Blanket", "Mattress"],
    correctAnswer: "Bed",
    ipa: "/bed/",
    type: "noun",
    meaning: "Cái giường",
    example: "It's time to go to bed and get some rest.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZnzv4hbrJKubvfECVCiZ-4akHvvG70Puigw&s",
    options: ["Bottle", "Can", "Jar", "Box"],
    correctAnswer: "Bottle",
    ipa: "/ˈbɑːtl/",
    type: "noun",
    meaning: "Cái chai",
    example: "Please remember to recycle your plastic bottle.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOwfYv8YZpZyuyXXbbTIBaW5hGyGufbvaA-Q&s",
    options: ["Code", "Text", "Image", "Video"],
    correctAnswer: "Code",
    ipa: "/koʊd/",
    type: "noun",
    meaning: "Mã lệnh",
    example: "The programmer wrote many lines of code to build the app.",
  },

  // Thực phẩm & Đồ uống
  {
    image:
      "https://www.alphafoodie.com/wp-content/uploads/2020/11/Orange-Juice-1-of-1.jpeg",
    options: ["Juice", "Milk", "Water", "Soda"],
    correctAnswer: "Juice",
    ipa: "/dʒuːs/",
    type: "noun",
    meaning: "Nước ép",
    example: "A glass of fresh orange juice is a great way to start the day.",
  },
  {
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    options: ["Soup", "Salad", "Sandwich", "Stew"],
    correctAnswer: "Salad",
    ipa: "/ˈsæləd/",
    type: "noun",
    meaning: "Rau trộn",
    example: "A Caesar salad is a popular choice for a light lunch.",
  },
  {
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    options: ["Fries", "Burger", "Hotdog", "Taco"],
    correctAnswer: "Burger",
    ipa: "/ˈbɜːrɡər/",
    type: "noun",
    meaning: "Bánh hăm-bơ-gơ",
    example: "This restaurant is famous for its delicious burger.",
  },
  {
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    options: ["Meal", "Dish", "Plate", "Cuisine"],
    correctAnswer: "Meal",
    ipa: "/miːl/",
    type: "noun",
    meaning: "Bữa ăn",
    example: "We enjoyed a wonderful three-course meal at the restaurant.",
  },
  {
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
    options: ["Pepperoni", "Mushroom", "Olive", "Cheese Pizza"],
    correctAnswer: "Cheese Pizza",
    ipa: "/tʃiːz ˈpiːtsə/",
    type: "noun",
    meaning: "Pizza phô mai",
    example: "A classic cheese pizza is simple yet delicious.",
  },
  {
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    options: ["Grilled Chicken", "Fried Fish", "Steak", "Pork Chop"],
    correctAnswer: "Grilled Chicken",
    ipa: "/ɡrɪld ˈtʃɪkɪn/",
    type: "noun",
    meaning: "Gà nướng",
    example: "Grilled chicken with vegetables is a healthy meal option.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6HhedQdurLUbPn70JFdb0jldFgv7dZQnYBw&s",
    options: ["Ice Cream", "Cake", "Cookie", "Donut"],
    correctAnswer: "Ice Cream",
    ipa: "/aɪs kriːm/",
    type: "noun",
    meaning: "Kem",
    example: "Let's get a scoop of ice cream for dessert.",
  },
  {
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800",
    options: ["Cheeseburger", "Hamburger", "Veggie Burger", "Fish Burger"],
    correctAnswer: "Cheeseburger",
    ipa: "/ˈtʃiːzbɜːrɡər/",
    type: "noun",
    meaning: "Bánh hăm-bơ-gơ phô mai",
    example: "I'll have a double cheeseburger with fries.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSygAUeHjV9DNWz5E2o9mxU39bwX3HPIS36rw&s",
    options: ["Coffee", "Tea", "Hot Chocolate", "Latte"],
    correctAnswer: "Coffee",
    ipa: "/ˈkɔːfi/",
    type: "noun",
    meaning: "Cà phê",
    example: "Many people can't start their day without a cup of coffee.",
  },
  {
    image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800",
    options: ["Ingredients", "Spices", "Herbs", "Seasoning"],
    correctAnswer: "Ingredients",
    ipa: "/ɪnˈɡriːdiənts/",
    type: "noun",
    meaning: "Nguyên liệu",
    example: "You should gather all the ingredients before you start cooking.",
  },

  // Địa điểm & Tòa nhà
  {
    image: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=800",
    options: ["House", "Apartment", "Castle", "Mansion"],
    correctAnswer: "House",
    ipa: "/haʊs/",
    type: "noun",
    meaning: "Ngôi nhà",
    example: "They live in a beautiful house in the suburbs.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS514npY16UiXjtkzkup2XvMe05W8UNQMLhOw&s",
    options: ["School", "Store", "Library", "College"],
    correctAnswer: "School",
    ipa: "/skuːl/",
    type: "noun",
    meaning: "Trường học",
    example: "Children go to school to learn.",
  },
  {
    image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800",
    options: ["Shop", "Store", "Market", "Mall"],
    correctAnswer: "Shop",
    ipa: "/ʃɑːp/",
    type: "noun",
    meaning: "Cửa hàng",
    example: "Let's go to the coffee shop for a break.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL3wqwAaYcESoKjYVaiMhXgULqAAU-TFkLEA&s",
    options: ["Hospital", "Clinic", "Pharmacy", "Doctor Office"],
    correctAnswer: "Hospital",
    ipa: "/ˈhɑːspɪtl/",
    type: "noun",
    meaning: "Bệnh viện",
    example: "The new hospital has state-of-the-art equipment.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSey2zLaG2Y3MRwAKdfvqVcO-lnGeDmMQf1kA&s",
    options: ["Airport", "Train Station", "Bus Stop", "Harbor"],
    correctAnswer: "Airport",
    ipa: "/ˈerpɔːrt/",
    type: "noun",
    meaning: "Sân bay",
    example: "We need to be at the airport three hours before our flight.",
  },
  {
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    options: ["Restaurant", "Cafe", "Bar", "Diner"],
    correctAnswer: "Restaurant",
    ipa: "/ˈrestərɑːnt/",
    type: "noun",
    meaning: "Nhà hàng",
    example: "This restaurant serves authentic Italian food.",
  },
  {
    image:
      "https://media.istockphoto.com/id/1450094329/photo/colorful-sunset-viewed-from-the-pink-sea-beach-with-soft-waves.webp?b=1&s=612x612&w=0&k=20&c=OSrd0Frh-qLvr8RfDCfsaIkNVA30CBq-nGBq621AcNk=",
    options: ["Beach", "Coast", "Shore", "Seaside"],
    correctAnswer: "Beach",
    ipa: "/biːtʃ/",
    type: "noun",
    meaning: "Bãi biển",
    example: "We spent the afternoon relaxing on the beach.",
  },
  {
    image: "https://images.unsplash.com/photo-1533109721025-d1ae7ee7c1e1?w=800",
    options: ["Bridge", "Tunnel", "Overpass", "Viaduct"],
    correctAnswer: "Bridge",
    ipa: "/brɪdʒ/",
    type: "noun",
    meaning: "Cây cầu",
    example: "The Golden Gate Bridge is an iconic landmark.",
  },
  {
    image: "https://images.unsplash.com/photo-1569949381669-ecf31ae8e613?w=800",
    options: ["Farm", "Ranch", "Orchard", "Vineyard"],
    correctAnswer: "Farm",
    ipa: "/fɑːrm/",
    type: "noun",
    meaning: "Nông trại",
    example: "They grow organic vegetables on their farm.",
  },
  {
    image: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800",
    options: ["City", "Town", "Village", "Metropolis"],
    correctAnswer: "City",
    ipa: "/ˈsɪti/",
    type: "noun",
    meaning: "Thành phố",
    example: "Paris is a beautiful city known for its art and culture.",
  },

  // Khác
  {
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800",
    options: ["Money", "Coin", "Bill", "Cash"],
    correctAnswer: "Money",
    ipa: "/ˈmʌni/",
    type: "noun",
    meaning: "Tiền",
    example: "You need to save money for your future.",
  },
  {
    image: "https://images.unsplash.com/photo-1530026405182-273c32de5878?w=800",
    options: ["Fire", "Flame", "Blaze", "Ember"],
    correctAnswer: "Fire",
    ipa: "/faɪər/",
    type: "noun",
    meaning: "Lửa",
    example: "We gathered around the fire to stay warm.",
  },
  {
    image: "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800",
    options: ["Article", "Headline", "Paragraph", "Newspaper"],
    correctAnswer: "Newspaper",
    ipa: "/ˈnuːzpeɪpər/",
    type: "noun",
    meaning: "Báo giấy",
    example: "My grandfather reads the newspaper every morning.",
  },
  {
    image: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800",
    options: ["Writing", "Drawing", "Painting", "Sketching"],
    correctAnswer: "Writing",
    ipa: "/ˈraɪtɪŋ/",
    type: "noun",
    meaning: "Sự viết lách",
    example: "Good writing is a crucial skill for communication.",
  },
  {
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtdiBTCfFZi4q6-Cs10oIFParTYg-ElfCG6g&s",
    options: ["Map", "Globe", "Atlas", "Chart"],
    correctAnswer: "Map",
    ipa: "/mæp/",
    type: "noun",
    meaning: "Bản đồ",
    example: "We used a map to navigate through the city.",
  },
  {
    image:
      "https.://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHSktJwxQfPo4BHwPyBlRiDipRmF8nulqSCg&s",
    options: ["Ball", "Sphere", "Globe", "Orb"],
    correctAnswer: "Ball",
    ipa: "/bɔːl/",
    type: "noun",
    meaning: "Quả bóng",
    example: "The children were playing with a colorful ball in the park.",
  },
];
export default vocabImages;
